### ISSUE TITLE
Could you add License?

### ISSUE THREAD

**Issue by LittleWat** [dweber019/apicurio-registry-artifact-operator#1]
Hello! I am currently using  https://github.com/Apicurio/apicurio-registry-content-sync-operator, but I prefer Golang and this repo looks nice! I am glad if you could add a License file to decide if I can use this repo or not.

**Comment by dweber019** [comment]
I added https://github.com/dweber019/apicurio-registry-artifact-operator/blob/master/LICENSE.
But notice that this was a first try and you should probably use the official one from apicurio.

**Comment by LittleWat** [comment]
Thanks!! Actually, I prefer Golang and will be glad if this replace the official Java one... 😅
